version: '3.4'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - database
    ports:
      - 5000:80
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: A&VeryComplex123Password
    ports:
      - 1433:1433
    volumes:
      - data:/var/opt/mssql
volumes:
  data:
    name: database1